#iphone
view.portfolio=name=View your proposed portfolio
adv.advisor=name=Contact Your Financial Advisor
retake.Questionnaire=name=Retake Questionnaire
close.Questionnaire=name=Close
accounts.analyzed=name=0 of 1 Account Analyzed has popup
analyze.cancel=name=Cancel