closeHPNotification=name=close
holdingsSummary=name=Holdings Summary
todaysValue=xpath=//XCUIElementTypeStaticText[@name ='AVAILABLE (SGD)']//following-sibling::XCUIElementTypeStaticText[1]
equityAwards=name=Equity Awards
equityActivity=name=Activity
orders.completed=name=Completed
orders.disclosures=name=Disclosures
equityHoldings=name=Holdings
holdings.awards=name=Awards
holdings.shares=name=Shares
EquityTransactions=name=Transactions
transactionsWelcome=name=Welcome to transactions on mobile!
EquityAwardsEducation=name=Awards Education
education.progress=name=My Progress
EquityNotify=name=Notifications
notifications,actionable=name=Actionable
Home=name=Home
hp.mywealth=name=My Wealth
mw.balances=name=Balances
mw.holdings=name=Holdings
mw.activity=name=Activity
mw.tools=name=Financial Tools