closeHPNotification=name=close
holdingsSummary=name=Holdings Summary
todaysValue=xpath=//XCUIElementTypeStaticText[@name ='AVAILABLE (SGD)']//following-sibling::XCUIElementTypeStaticText[1]
equityAwards=name=Equity Awards
equityActivity=name=Activity
equityHoldings=name=Holdings
EquityTransactopns=name=Transactions
EquityAwardsEducation=name=Awards Education
EquityNotify=name=Notifications
Home=name=Home