debug.next=xpath=//*[@label="Next"]
debug.pw=xpath=//*[@value="Password"]
################# login page

#Ipad
home.getintouch=xpath=//XCUIElementTypeNavigationBar//XCUIElementTypeButton
login.message=xpath=//*[@label="Welcome to UBS. Please sign in."]
field.username=xpath=//XCUIElementTypeTextField
field.password=xpath=//XCUIElementTypeSecureTextField
login.signin.btn=xpath=//*[@name="SignInView.signInButton"]

iPad.signin.btn=xpath=//*[@label="Sign In"]
login.next=xpath=//*[@value='Next']
ipad.face.decline=xpath=//XCUIElementTypeButton[@label="Not Now"]
home.glance=xpath=//*[@label="See why cash matters"]/following-sibling::XCUIElementTypeButton[1]
glance.whyMatters=xpath=//*[@name="bankingHubWhyCashMattersButton"]
# iphone
login.password.iphone=xpath=//*[@value="Password"]
login.next.iphone=name=Next:
login.username.iphone=xpath=//*[@value="Username"]
login.OK.got.it=name=OK, got it
login.Not.Now=name=Not now
#//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]/XCUIElementTypeOther[2]
#//XCUIElementTypeApplication/XCUIElementTypeWindow[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeScrollView[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[3]
##################### Advice Advantage




#//XCUIElementTypeCell[@label="UBS Advice Portfolio Program"]//*[@label="UBS Advice Portfolio Program"]
advice.timeWeightedReturn=xpath=//*[@label="Net Time-Weighted Return:"]
advice=name=Advice Advantage
adviceMenuChoice=xpath=//*[@name="Guidance"]
explore.advice=name=Explore UBS Advice Advantage
advice.portfolio.guidance=xpath=//*[@name="Guidance"]
zero.accounts=xpath=//*[@label="1 of 11 Accounts Analyzed has popup"]

#1 of (.*) accounts analyzed
select.accounts=name=Select accounts to include
advice.cancel=name=Cancel
advisor.close=name=Close
advice.topClose=xpath=//*[@label="Close"]
advice.bottomCancel=xpath=//*[@label="Cancel"]


# ###########################   main page
main.net.balance=xpath=//*[@label="Net Balance"]
main.accounts=-ios predicate string=type == 'XCUIElementTypeStaticText' AND value == 'Accounts'
iphone.main.accounts=xpath=//XCUIElementTypeButton[@label='Accounts']
main.statementtax=xpath=//*[@name="Statements & Tax Forms"]
statementtax.taxforms=xpath=//*[@label="Tax Forms"]
statementtax.AllOf2Accounts=xpath=(//*[@name="All 5 accounts selected"])[1]
statementtax.accountstatement=xpath=//*[@label="Account Statement"]
statementtax.ccstatements=xpath=//*[@label="Credit Card Statements"]
statementtax.houseStateWSummary=xpath=//*[@label="Household Statement w/Summary"]
statementtax.houseStaSummary=xpath=//*[@label="Household Statement Summary"]
statementtax.commodityFX=xpath=//*[@label="Commodity/FX Statement"]
statementtax.account=xpath=//*[contains(@name,'No Account')]
statementtax.back=xpath=//*[@label="cdx arrowBigLeftIcon"]
statementtax.CCaccount=xpath=(//*[@label="UN 91973 Demo Cred Card"])[1]
statementtax.liqiudity=xpath=(//*[@label="Liquidity"]


#///////////////////////////////////////////////////////////////////
statement.tax.header=xpath=//*[@label="Statements & Tax Forms"]
#/////////////////////////////////////////////////////////////////////

home=xpath=//*[@label="Home"]
home.cashGlanceLink=xpath=//*[@name="HomeCashSummaryView.goToCashButton"]
main.milestones=name=Milestones
main.ipad.milestone=xpath=//*[@label="Milestones"]
main.profile=name=Profile
main.menu=name=Menu
main.sign.out=name=Sign out
field.bioPassword=xpath=//XCUIElementTypeScrollView/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]
#//XCUIElementTypeButton[@label="Sign out"]
# Iphone
menu.iphone=xpath=//*[@label="Menu"]
banking.services=xpath=//*[@label="Banking Services"]
home.asof=xpath=//XCUIElementTypeStaticText[contains(@value,'AS OF')][last()]
iphone.cash.glance=xpath=//*[@name="HomeNetBalanceView.rootView"]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeStaticText[1]
iphone.signin=name=Sign in
iphone.welcometoubs=name=Welcome to UBS
iphone.welcome.signin=xpath=//*[@label="Sign In to UBS"]





######## Banking services
#iphone

glance=name=At a Glance
bankingServices.glance=xpath=//*[@label="At a Glance"]
glance.recent=name=Recent Cash & Credit Activity
transfer.funds=xpath=//*[@name="secondaryMenu.transferFunds"]


funds.move=name=Move funds across UBS accounts
pay.bills=name=Pay Bills
bills=name=Pay bills outside of UBS
bills.payment=name=Choose a USB Withdrawal Account
pay.ubs=name=Pay UBS Credit Card and Credit Lines
pay.credit=name=Take care of UBS credit card payments
deposit.check=name=Deposit Checks
noaccount=name=No eligible accounts
investment.header=name=investmentHeaderCell
investment.title=xpath=//*[@name="Investment Assets"]#total.value=xpath=//XCUIElementTypeTable/XCUIElementTypeCell[1]/XCUIElementTypeStaticText[2]
total.value=xpath=//*[@label="CHANGE IN VALUE"]/following-sibling::XCUIElementTypeStaticText[1]
ipad.total.value=xpath=(//*[@name="Current Balance"])[1]//XCUIElementTypeStaticText[contains(@name,'$')][1]
ipad.accounts.ubsorAll=//*[@value="UBS"]
schedule.transfers=name=Scheduled Transfers
ipad.schedule.transfers=name=Scheduled Transfers
transfering.out=name=Transferring out


#Ipad
glance.value=xpath=//XCUIElementTypeStaticText[@value="UBS Cash - Total Value"]/following-sibling::XCUIElementTypeButton[1]
ipad.credit=xpath=//*[@label="Pay UBS Credit Card or Line"]


#############    Accounts  ############


#Iphone
iphone.accounts.balances=name=Balances
iphone.priorday=name=PRIOR DAY
iphone.accounts.activity.detail=name=xcdx arrowBigRightIcon
iphone.financialtools.msg=name=Includes UBS and external accounts
iphone.intraday=name=INTRADAY
iphone.investments=name=Investments 
iphone.change.value=name=CHANGE IN VALUE
iphone.all=name=All
iphone.investment.assets=name=Investment Assets
iphone.holdings.cash=name=Cash
iphone.total.value=name=TOTAL VALUE
#iphone.ubs=-ios predicate string=type == 'XCUIElementTypeStaticText' AND value == 'UBS'
#//XCUIElementTypeTable/XCUIElementTypeOther[2]//*[@type="XCUIElementTypeStaticText"][2]
iphone.ubs=xpath=//*[@value='UBS']
ipad.ubs=xpath=//XCUIElementTypeButton[@label='Add external accounts']/following-sibling::XCUIElementTypeOther/XCUIElementTypeStaticText[@name='UBS']
iphone.holdings.grandTotal=xpath=(/descendant-or-self::node()/XCUIElementTypeStaticText[@value="TOTAL VALUE"])[1]/following-sibling::XCUIElementTypeStaticText[1]
iphone.holdings.cashTotal=xpath=(/descendant-or-self::node()/XCUIElementTypeStaticText[@value="TOTAL VALUE"])[2]/following-sibling::XCUIElementTypeStaticText[1]
iphone.activity.first=xpath=(/descendant-or-self::node()/*[@name="cdx arrowBigRightIcon"])[1]
activity.amount=xpath=//XCUIElementTypeStaticText[@value="AMOUNT"]/preceding-sibling::XCUIElementTypeStaticText[1]
activity.back=name=cdx arrowBigLeftIcon
activity.filterAccounts=xpath=//XCUIElementTypeTable/XCUIElementTypeOther[1]/XCUIElementTypeButton[1]
activity.selectAll=xpath=//XCUIElementTypeButton[@label="Select all"]
activity.apply=xpath=//XCUIElementTypeButton[@label="Apply"]
#Ipad
ipad.activity.filterAccounts=xpath=//XCUIElementTypeButton[@label="3 accounts selected"]
ipad.activity.selectAll=xpath=//*[@value="Select all"]
ipad.activity.apply=xpath=//XCUIElementTypeButton[@label="Apply"]
ipad.activity.first=xpath=//XCUIElementTypeTable/XCUIElementTypeCell[1]/XCUIElementTypeButton[2]
accounts.balances=name=Balances
accounts.currentBalance=name=Current Balance
accounts.holdings=-ios predicate string=type == 'XCUIElementTypeStaticText' AND value == 'Holdings'
holdings.cash=name=Cash

accounts.activity=name=Activity
activity.account=name=Account No.
holdings.all=xpath=//*[@content-desc="All"]
ipad.activity.account=xpath=//XCUIElementTypeOther[@name='Date']/XCUIElementTypeStaticText[@label='Account No.']
filter.apply=name=Apply
ytd=name=Year to date
ytd.iphone=name=YEAR TO DATE
iphone.movenext=xpath=//*[@name="cdx-arrowBigRightIcon"]
iphone.account.select.all.button=name=Select all
iphone.account.apply.button=name=Apply
filter.btn=xpath=//*[@name="cdx-arrowBigRightIcon"]/following-sibling::XCUIElementTypeButton
ipad.filter=xpath=(//XCUIElementTypeButton[@label='Filter']/ancestor::XCUIElementTypeOther/XCUIElementTypeButton)[3]
activity.type=name=Activity Type
ipad.activity.type=xpath=//XCUIElementTypeOther[@name='Date']/XCUIElementTypeStaticText[@label='Activity Type']
accounts.financial.tools=name=Financial Tools
financial.tools.msg=name=Information on this page is refreshed daily and does not reflect real time values
net.balance=name=Net Balance
cash.flow.iphone=name=Cash Flow
cash.flow=xpath=//XCUIElementTypeStaticText[@name='Cash Flow']
cash.flow.msg=name=Know how your money moves
cash.flow.spending=name=Spending
cash.flow.expenses=name=Expense Analysis
back=xpath=//*[@label="cdx arrow small left"]
balances.priorday=name=Prior day
ipad.balances.selected.type=xpath=//*[@name='Intraday']/following-sibling::XCUIElementTypeOther/XCUIElementTypeStaticText
ipad.balances.priorday=xpath=//*[@name='Intraday']/following-sibling::XCUIElementTypeStaticText
prior.day.investments=name=investmentHeaderCell
ipad.prior.day.investments=xpath=//*[@name='investmentHeaderCell']/XCUIElementTypeStaticText[@name='Investments ']
balances.intraday=name=Intraday
balances.all=name=All
ipad.balances.selected.accounts=xpath=//*[@name='UBS']/following-sibling::XCUIElementTypeOther/XCUIElementTypeStaticText
ipad.balances.all=xpath=//*[@name='UBS']/following-sibling::XCUIElementTypeStaticText
all.assets=name=Assets
ipad.all.assets=xpath=//XCUIElementTypeTable//XCUIElementTypeButton[@label='Assets']
ubs=name=UBS
iphone.djia.asof=xpath=//*[@label='NASDAQ COMPOSITE INDEX']/following-sibling::XCUIElementTypeStaticText[starts-with(@label,'AS OF')]
iphone.nasdaq.asof=xpath=//*[@label='NASDAQ Composite']/following-sibling::XCUIElementTypeStaticText[starts-with(@label,'AS OF')]
holdings.ubs.change=name=Change in Value
holdings.quantity=name=Quantity
activity.amounts=xpath=//XCUIElementTypeTable/XCUIElementTypeCell[3]//XCUIElementTypeStaticText[starts-with(@label,'$')]
ipad.holdings.grandTotal=xpath=(/descendant-or-self::node()/XCUIElementTypeStaticText[@value="Total Value"])[1]/following-sibling::XCUIElementTypeStaticText[1]
iphone.activity.back=xpath=//XCUIElementTypeNavigationBar//XCUIElementTypeButton
# Milestone
mile.scouts=name=World tour
mile.back.ipad=name=Button
mile.bsa=name=$11 per year
mile.
mile.resources=name=Resources
mile.back=name=cdx arrowBigLeftIcon
mile.add=name=Add a milestone
mile.travel=name=Travel
mile.name=name=MilestoneNameComponentViewCell
mile.next=name=Next
mile.start=name=milestoneStartYear
mile.year=name=2024
mile.amount=name=milestoneAmount
mile.add.keyboard=xpath=//*[@label="addMilestoneTableView"]/XCUIElementTypeOther[1]
milestones.page=name=The Road Ahead
milestone.created=xpath=//*[@label="London"]
milestone.delete=name=Remove this milestone
milestone.delete.confirm=name=Delete
retirement=name=Retirement
something.went.wrong=xpath=//*[@label="Sorry, something went wrong"]

#Ipad
xbutton=xpath=//XCUIElementTypeButton[@label="Button"]

###################### Profile ##############

#iphone
profile.iphone.primary=name=PRIMARY
profile.iphone.team=name=My UBS Team
profile.iphone.advice=name=Chris
profile.meetings=name=Meetings
profile.no.meeting=name=No upcoming meetings
profile.settings=name=Settings
profile.card=name=Card Security
profile.nocard=name=There is no card to manage
profile.card.back=name=cdx arrowBigLeftIcon
support.close=xpath=//*[@label="cdx close small"]
feedback.send=xpath=//*[@label="Submit"]
feedback.ten=xpath=//*[@label="10,Completely satisfied"]
feedback.yes=xpath=//*[@label="Yes"]
feedback.back=xpath=//*[@label="back"]
profile.my.information=name=My Information
Myinfo.back=//*[@label="Back"]

#ipad
profile.primary=name=Primary
profile.relationship=name=Relationships
profile.team=xpath=//*[@label="Empty list"]/XCUIElementTypeOther[2]/XCUIElementTypeButton[4]
close.tome=name=Close to Me
mindset=name=Mindsets and Interests
mindset.msg=name=Has your outlook changed?
settings=xpath=//*[@label="icon menu settings"]
iPadSettings=xpath=//*[@label="Settings"]
information=name=Information
profile.back=xpath=//*[@label="Back"]
profile.return=xpath=//XCUIElementTypeButton[@label='cdx arrow small left']
support=name=Support
iphone.support.need.assistance=xpath=//*[@label='Need assistance? Call']
iphone.menu.support=xpath=//XCUIElementTypeTable//XCUIElementTypeStaticText[@name='Support']
support.done=xpath=//*[@value="Done"]
feedback=xpath=//*[@value="Feedback"]
feedback.cancel=xpath=//*[@value="Cancel"]
external.pro=name=External Professionals
community.bsa=name=BSA
ipad.card.security=xpath=//*[@label="Card On/Off"]

######## Menu Options ######
#iphone
relationship.community=name=Close to Me
#  //*[@label="Empty list"]/XCUIElementTypeOther[2]/XCUIElementTypeButton[3]
relationship.team=name=My UBS Team
relationship.advice=name=UBS Wealth Advice Center
interest=name=Has your perspective changed?
settings.reset=name=Reset Password
legal.cancel=Name=Cancel

##FA
#Ipad
contact=xpath=//XCUIElementTypeButton[@label="Contact your Financial Advisor"]
tollfree=name=Chris
ipad.contactnumber=name=4415
close=name=Close
ipad.setttings.close=xpath=//*[@label="cdx arrow small left"]