debug.next=xpath=//*[@label="Next"]
debug.pw=xpath=//*[@value="Password"]
################# login page

#Ipad
login.message=xpath=//*[@label="Welcome to UBS. Please sign in."]
field.username=xpath=//XCUIElementTypeTextField
field.password=xpath=//XCUIElementTypeSecureTextField
login.signin.btn=name=Sign in
login.next=name=Next
ipad.face.decline=name=No
home.glance=xpath=//*[@label="See why cash matters"]/following-sibling::XCUIElementTypeButton[1]
# iphone
field.password.iphone=xpath=//*[@value="Password"]
login.next.iphone=name=Next:
username.iphone=xpath=//*[@value="Username"]


##################### Advice Advantage
advice=name=Advice Advantage
explore.advice=name=Explore UBS Advice Advantage
zero.accounts=name=0 of 1 Account Analyzed has popup
select.accounts=name=Select accounts to include
advice.cancel=name=Cancel
advisor.close=name=Close



# ###########################   main page
main.net.balance=id=Net Balance
main.accounts=name=Accounts
home=name=Home
main.milestones=name=Milestones
main.ipad.milestone=xpath=//*[@name='Milestones' and @height='28']
main.profile=name=Profile
main.sign.out=name=Sign out
# Iphone
menu.iphone=name=Menu
banking.services=name=Banking Services
home.asof=xpath=//XCUIElementTypeStaticText[contains(@value,'AS OF')][last()]
iphone.cash.glance=name=dashBoardTotalCash





######## Banking services
#iphone

glance=name=At a Glance
glance.recent=name=Recent Cash & Credit Activity
transfer.funds=name=Transfer Funds
funds.move=name=Move funds across UBS accounts
pay.bills=name=Pay Bills
bills=name=Pay bills outside of UBS
pay.ubs=name=Pay UBS Credit Card and Credit Lines
pay.credit=name=Take care of UBS credit card payments
deposit.check=name=Deposit Checks
noaccount=name=No eligible accounts
total.value=xpath=//XCUIElementTypeStaticText[contains(@name,'$')][1]
schedule.transfers=name=Manage Scheduled Transfers
transfering.out=name=Transferring out


#Ipad
glance.value=xpath=//XCUIElementTypeStaticText[@value="UBS Cash - Total Value"]/following-sibling::XCUIElementTypeButton[1]
ipad.credit=xpath=//*[contains(@name,'Credit Card and Credit Line')]


#############    Accounts  ############


#Iphone
iphone.accounts.balances=name=Balances
iphone.priorday=name=PRIOR DAY
iphone.accounts.activity.detail=name=xcdx arrowBigRightIcon
iphone.financialtools.msg=name=All Accounts
iphone.intraday=name=INTRADAY
iphone.investments=name=Investments 
iphone.change.value=name=CHANGE IN VALUE
iphone.all=name=All
iphone.investment.assets=name=Investment Assets
iphone.holdings.cash=name=Cash
iphone.total.value=name=TOTAL VALUE
iphone.ubs=name=UBS
iphone.holdings.grandTotal=xpath=(/descendant-or-self::node()/XCUIElementTypeStaticText[@value="TOTAL VALUE"])[1]/following-sibling::XCUIElementTypeStaticText[1]
iphone.holdings.cashTotal=xpath=(/descendant-or-self::node()/XCUIElementTypeStaticText[@value="TOTAL VALUE"])[2]/following-sibling::XCUIElementTypeStaticText[1]
iphone.activity.first=xpath=(/descendant-or-self::node()/*[@name="cdx arrowBigRightIcon"])[1]
activity.amount=xpath=//XCUIElementTypeStaticText[@value="AMOUNT"]/preceding-sibling::XCUIElementTypeStaticText[1]
activity.back=name=cdx arrowBigLeftIcon
#Ipad
accounts.balances=name=Balances
accounts.currentBalance=name=Current Balance
accounts.holdings=name=Holdings
holdings.cash=name=Cash
accounts.activity=name=Activity
activity.type=name=Activity Type
accounts.financial.tools=name=Financial Tools
financial.tools.msg=name=Information on this page is refreshed daily and does not reflect real time values
net.balance=name=Net Balance
cash.flow=name=Cash Flow
cash.flow.msg=name=Know how your money moves
cash.flow.spending=name=Spending
cash.flow.expenses=name=Expense Analysis
back=name=cdx arrow small left
balances.priorday=name=Prior day
prior.day.investments=name=investmentHeaderCell
balances.intraday=name=Intraday
balances.all=name=All
all.assets=name=Assets
ubs=name=UBS
holdings.ubs.change=name=Change in Value
holdings.quantity=name=Quantity
activity.amounts=xpath=//XCUIElementTypeStaticText[starts-with(@label,'$')]
ipad.holdings.grandTotal=xpath=(/descendant-or-self::node()/XCUIElementTypeStaticText[@value="Total Value"])[1]/following-sibling::XCUIElementTypeStaticText[1]

# Milestone
mile.scouts=name=donation to the Scouts
mile.back.ipad=name=Button
mile.bsa=name=For BSA
mile.resources=name=Resources
mile.back=name=cdx arrowBigLeftIcon
mile.add=name=Add a milestone
mile.travel=name=Travel
mile.name=name=MilestoneNameComponentViewCell
mile.next=name=Next
mile.start=name=milestoneStartYear
mile.year=name=2024
mile.amount=name=milestoneAmount
mile.add.keyboard=xpath=//*[@label="addMilestoneTableView"]/XCUIElementTypeOther[1]
milestones.page=name=The road ahead
milestone.created=xpath=//*[@label="London"]
milestone.delete=name=Remove this milestone
milestone.delete.confirm=name=Delete
retirement=name=Retirement

#Ipad
xbutton=name=Button

###################### Profile ##############

#iphone
profile.iphone.primary=name=PRIMARY
profile.iphone.team=name=My UBS Team
profile.iphone.advice=name=UBS Wealth Advice Center
profile.meetings=name=Meetings
profile.no.meeting=name=No upcoming meetings
profile.settings=name=Settings
profile.card=name=Card Security
profile.nocard=name=There is no card to manage
profile.card.back=name=cdx arrowBigLeftIcon

#ipad
profile.primary=name=Primary
profile.relationship=name=Relationships
profile.team=name=UBS Team
close.tome=name=Close to Me
mindset=name=Mindsets and Interests
mindset.msg=name=Has your outlook changed?
settings=name=Settings
information=name=Information
profile.back=name=cdx arrow small left
support=name=Support
support.done=name=Done
feedback=name=Feedback
feedback.cancel=name=Cancel
external.pro=name=External Professionals
community.bsa=name=BSA
######## Menu Options ######
#iphone
relationship.community=name=Community
relationship.team=name=My UBS Team
relationship.advice=name=UBS Wealth Advice Center
interest=name=Has your perspective changed?
settings.reset=name=Reset Password

##FA
#Ipad
contact=name=Contact your Financial Advisor
tollfree=name=Toll Free
close=name=Close