
################# login page

#Ipad
login.message=xpath=//*[@label="Welcome to UBS. Please sign in."]
field.username=xpath=//AppiumAUT/XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeButton[1]
field.password=xpath=//XCUIElementTypeSecureTextField
login.signin.btn=name=Sign in
login.next=name=Next
# iphone
field.password.iphone=xpath=//*[@value="Password"]
login.next.iphone=name=Next:
username.iphone=xpath=//*[@value="Username"]




# ###########################   main page
main.net.balance=id=Net Balance
main.accounts=name=Accounts
home=name=Home
main.milestones=xpath=//XCUIElementTypeStaticText[@label='Milestones' and @hittable='true']
main.profile=name=Profile
main.sign.out=name=Sign out
# Iphone
menu.iphone=name=Menu



#############    Accounts  ############


#Iphone
iphone.accounts.balances=name=xBalances
iphone.priorday=name=PRIOR DAY



#Ipad
accounts.balances=name=Balances
accounts.currentBalance=name=Current Balance
accounts.holdings=name=Holdings
holdings.cash=name=Cash
accounts.activity=name=Activity
activity.type=name=Activity Type
accounts.financial.tools=name=Financial Tools
financial.tools.msg=name=Information on this page is refreshed daily and does not reflect real time values
net.balance=name=Net Balance
cash.flow=name=Cash Flow
cash.flow.msg=name=Know how your money moves
cash.flow.spending=name=Spending
cash.flow.expenses=name=Expense Analysis
back=name=cdx arrow small left

# Milestone
mile.add=name=Add a milestone
mile.travel=name=Travel
mile.name=name=MilestoneNameComponentViewCell
mile.next=name=Next
mile.start=name=milestoneStartYear
mile.year=name=2024
mile.amount=name=milestoneAmount
mile.add.keyboard=xpath=//*[@label="addMilestoneTableView"]/XCUIElementTypeOther[1]
milestones.page=name=The road ahead
milestone.created=xpath=//*[@label="London"]
milestone.delete=name=Remove this milestone
milestone.delete.confirm=name=Delete

###################### Profile ##############
#iphone
profile.iphone.primary=name=PRIMARY
profile.iphone.team=name=My UBS Team
profile.iphone.advice=name=UBS Wealth Advice Center

#ipad
profile.primary=name=Primary
profile.relationship=name=Relationships
profile.team=name=UBS Team

