closeHPNotification=xpath=close
holdingsSummary=name=Holdings Summary
todaysValue=xpath=//XCUIElementTypeStaticText[@name ='AVAILABLE (USD)']//following-sibling::XCUIElementTypeStaticText[1]
equityAwards=xpath=//*[@resource-id="com.ubs.clientmobile:id/bottom_nav_equity_awards"]
equityActivity=xpath=//*[@text="Activity"]
orders.completed=xpath=//*[@text="Completed"]
orders.disclosures=xpath=//*[@text="Disclosures"]
equityHoldings=name=Holdings
holdings.awards=name=Awards
holdings.shares=name=Shares
EquityTransactions=name=Transactions
transactionsWelcome=name=Welcome to transactions on mobile!
EquityAwardsEducation=name=Awards Education
education.progress=name=My Progress
EquityNotify=name=Notifications
notifications,actionable=name=Actionable
Home=name=Home
hp.mywealth=name=My Wealth
mw.balances=name=Balances
mw.balances.assets=name=Assets
mw.balances.investmentAssets=name=Investment Assets
mw.holdings=name=Holdings
mw.holdings.none=name=No holdings found for this account.
mw.activity=name=Activity
mw.activity.none=name=No activities match the selected criteria.
mw.tools=name=Financial Tools
mw.tools.netWorth=name=Net Worth
cashFlow=name=Cash Flow
know.moves=name=Know how your money moves
spending=name=Spending
expense.analysis=name=Expense Analysis

## Menu ##
my.info=name=My Information
username=name=RE008_CUN
settings=name=Settings
ew.settings=name=Equity Awards Settings
support=name=Support
market.hours=name=Market Hours and Holidays
legal=name=Legal and Disclosures
valuation=name=Valuation and Assets Information
legal.cancel=name=Cancel

get.in.touch=name=Get in touch
toll.free=name=TOLL FREE
touch.close=name=Close