closeHPNotification=xpath=close
holdingsSummary=name=Holdings Summary
todaysValue=xpath=//XCUIElementTypeStaticText[@name ='AVAILABLE (USD)']//following-sibling::XCUIElementTypeStaticText[1]
equityAwards=xpath=//*[@resource-id="com.ubs.clientmobile:id/bottom_nav_equity_awards"]
equityActivity=xpath=//*[@text="Activity"]
orders.completed=xpath=//*[@text="Completed"]
orders.disclosures=xpath=//*[@text="Disclosures"]
equityHoldings=xpath=//*[@text="Holdings"]
holdings.awards=xpath=//*[@text="Awards"]
holdings.shares=xpath=//*[@text="Shares"]
EquityTransactions=xpath=//*[@text="Transactions"]
transactionsWelcome=text=Welcome to transactions on mobile!
EquityAwardsEducation=xpath=//*[@text="Awards education"]
education.progress=text=My Progress
EquityNotify=xpath=//*[@text="Notifications"]
notifications,actionable=text=Actionable
Home=xpath=//*[@text="Home"]
hp.mywealth=xpath=//*[@text="My wealth"]
mw.balances=xpath=//*[@text="Balances"]
mw.balances.assets=text=Assets
mw.balances.investmentAssets=text=Investment assets
mw.holdings=xpath=//*[@text="Holdings"]
mw.holdings.none=text=No holdings found for this account.
mw.activity=xpath=//*[@text="Activity"]
mw.activity.none=text=No activities match the selected criteria.
mw.tools=xpath=//*[@text="Financial tools"]
mw.tools.netWorth=text=Net balance
cashFlow=text=Cash Flow
know.moves=text=Know how your money moves
spending=text=Spending
expense.analysis=text=Expense Analysis

## Menu ##
my.info=xpath=//*[@text="My information"]
username=xpath=//*[@text="RE008_CUN"]
settings=xpath=//*[@resource-id="com.ubs.clientmobile:id/menu_settings"]
ew.settings=xpath=//*[@text="Equity awards settings"]
support=xpath=//*[@text="Support"]
market.hours=xpath=//*["Market hours and holidays"]
legal=xpath=//*[@text="Legal and disclosures"]
valuation=xpath=//*[@text="Valuation and Assets Information"]
legal.cancel=xpath=//*[@resource-id="com.ubs.clientmobile:id/image_close_support"]

get.in.touch=xpath=//*[@text="Get in touch"]
toll.free=xpath=//*[@text="Toll Free"]
touch.close=xpath=//*[@text="Close"] 