debug.next=xpath=//*[@label="Next"]
debug.pw=xpath=//*[@value="Password"]
################# login page
field.bioPassword=xpath=//*[@resource-id="com.ubs.clientmobile:id/textinput_placeholder"]
field.bioDeviceName=xpath=(//*[@resource-id="com.ubs.clientmobile:id/custom_edittext"])[2]

#Ipad
login.message=xpath=//*[@label="Welcome to UBS. Please sign in."]
field.username=xpath=//*[@text="Username"]
field.password=xpath=//*[@text="Password"]
login.signin.btn=xpath=//*[@resource-id="com.ubs.clientmobile:id/btn_sign_in"]
login.next=xpath=//*[@value='Next']
ipad.face.decline=name=No
home.glance=xpath=//*[@label="See why cash matters"]/following-sibling::XCUIElementTypeButton[1]
# android
login.password.android=xpath=//*[@value="Password"]
login.next.android=name=Next:
login.username.android=xpath=//*[@value="Username"]
login.OK.got.it=name=OK, got it
login.Not.Now=xpath=//*[@resource-id="com.ubs.clientmobile:id/btn_not_now"]


################### Advice Advantage
advice=xpath=//*[@resource-id="com.ubs.clientmobile:id/bottom_nav_milestones"]
adviceMenuChoice=xpath=//*[@text="Guidance"]
explore.advice=text=Explore UBS Advice Advantage
zero.accounts=text=1 of 7 Account Analyzed
select.accounts=text=Select accounts to include
advice.cancel=text=Cancel
advisor.close=xpath=//*[@resource-id="com.ubs.clientmobile:id/toolbar_right_title"]



# ###########################   main page
main.net.balance=xpath=//*[@resource-id="com.ubs.clientmobile:id/label_net_balance"]
main.accounts=-ios predicate string=type == 'XCUIElementTypeStaticText' AND value == 'Accounts'
android.main.accounts=xpath=//*[@resource-id="com.ubs.clientmobile:id/bottom_nav_accounts"]

home=xpath=//*[@text="Home"]
main.milestones=xpath=//*[@resource-id="com.ubs.clientmobile:id/bottom_nav_milestones"]
main.ipad.milestone=xpath=//*[@name='Milestones' and @height='28']
main.profile=name=Profile
main.sign.out=xpath=//*[@resource-id="com.ubs.clientmobile:id/sign_out"]
#//XCUIElementTypeButton[@label="Sign out"]
# android
#menu.android=name=Menu
menu.android=xpath=//*[@resource-id="com.ubs.clientmobile:id/bottom_nav_menu"]//*[@resource-id="com.ubs.clientmobile:id/navigation_bar_item_icon_view"]
banking.services=xpath=//*[@resource-id="com.ubs.clientmobile:id/bottom_nav_banking_services"]//*[@resource-id="com.ubs.clientmobile:id/navigation_bar_item_icon_view"]
home.asof=xpath=//*[@resource-id="com.ubs.clientmobile:id/rv_market_data"]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/*[@resource-id="com.ubs.clientmobile:id/tv_timestamp"]
android.cash.glance=xpath=//*[@resource-id="com.ubs.clientmobile:id/tv_cash_available"]
android.signin=name=Sign in



main.statementtax=xpath=//*[@text="Statements & Tax Forms"]
statementtax.taxforms=xpath=//*[@text="Tax Forms"]
statementtax.accountstatement=xpath=//*[@text="Account Statement"]
statementtax.ccstatements=xpath=//*[@text="Credit Card Statements"]
statementtax.houseStateWSummary=xpath=//*[@text="Household Statement w/Summary"]
statementtax.houseStaSummary=xpath=//*[@text="Household Statement Summary"]
statementtax.commodityFX=xpath=//*[@text="Commodity/FX Statement"]
statementtax.account=xpath=//*[contains(@name,'UN 91973')]
statementtax.back=xpath=//*[@resource-id="com.ubs.clientmobile:id/toolbar_back"]
statementtax.CCaccount=xpath=(//*[@text="UN 91973 Demo Cred Card"])[1]


######## Banking services
#android

glance=xpath=//*[@text="At a Glance"]
glance.recent=name=Recent Cash & Credit Activity
transfer.funds=xpath=//*[@text="Transfer Funds"]


funds.move=name=Move funds across UBS accounts
pay.bills=name=Pay Bills
bills=name=Pay bills outside of UBS
bills.payment=xpath=//*[@text="Make a payment"]
pay.ubs=xpath=//*[@text="Pay UBS Credit Card and Credit Lines"]
pay.credit=name=Take care of UBS credit card payments
deposit.check=xpath=//*[@text="Deposit Checks"]
noaccount=name=No eligible accounts
investment.header=name=investmentHeaderCell
investment.title=xpath=//*[@name="Investment Assets"]
################################################################RRRRRRRJJJJRRRRRRf
total.value=xpath=//*[@resource-id="com.ubs.clientmobile:id/investment_fragment"]//*[@resource-id="com.ubs.clientmobile:id/balances_list_view"]/android.view.ViewGroup[1]/android.widget.TextView[4]
android.total.assets=xpath=//*[@resource-id="com.ubs.clientmobile:id/tv_total_assets"]
schedule.transfers=xpath=//*[@content-desc="Scheduled Transfers"]
transfering.out=name=Transferring out


#Ipad
glance.value=xpath=//*[@resource-id="com.ubs.clientmobile:id/tv_cashval_total_cash_value"]
ipad.credit=xpath=//*[contains(@name,'Credit Card and Credit Line')]


#############    Accounts  ############


#android
android.accounts.balances=xpath=//*[@text="Balances"]
android.priorday=xpath=//*[@resource-id="com.ubs.clientmobile:id/radiobuttonPriorday"]
android.accounts.activity.detail=name=xcdx arrowBigRightIcon
android.financialtools.msg=xpath=//*[@text="All Accounts"]
android.intraday=xpath=//*[@resource-id="com.ubs.clientmobile:id/radiobuttonIntraday"]
android.investments=name=Investments 
android.change.value=name=CHANGE IN VALUE
android.all=xpath=//*[@content-desc="All"]
android.investment.assets=xpath=//*[@text="Investment Assets"]
android.holdings.cash=xpath=//*[@resource-id="com.ubs.clientmobile:id/list_view"]/android.widget.LinearLayout[1]/android.view.ViewGroup[1]/android.widget.LinearLayout[2]/android.widget.LinearLayout[1]//*[@resource-id='com.ubs.clientmobile:id/header3']
android.total.value=name=TOTAL VALUE
#//*[@resource-id="com.ubs.clientmobile:id/tv_total_assets"]
#android.ubs=-ios predicate string=type == 'XCUIElementTypeStaticText' AND value == 'UBS'
android.ubs=xpath=//*[@content-desc="UBS"]
ipad.ubs=xpath=//XCUIElementTypeButton[@label='Add external accounts']/following-sibling::XCUIElementTypeOther/XCUIElementTypeStaticText[@name='UBS']
android.holdings.grandTotal=xpath=//*[@resource-id="com.ubs.clientmobile:id/list_view"]/android.widget.LinearLayout[1]/android.view.ViewGroup[1]/android.widget.LinearLayout[2]/android.widget.LinearLayout[1]//*[@resource-id='com.ubs.clientmobile:id/header3']
android.holdings.cashTotal=xpath=(/descendant-or-self::node()/XCUIElementTypeStaticText[@value="TOTAL VALUE"])[2]/following-sibling::XCUIElementTypeStaticText[1]
android.activity.first=//*[@resource-id="com.ubs.clientmobile:id/rv_investment_list"]/android.view.ViewGroup[2]/android.widget.TextView[3]
activity.amount=xpath=//hierarchy/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/androidx.recyclerview.widget.RecyclerView[1]/android.view.ViewGroup[3]/android.widget.TextView[2]
activity.back=name=cdx arrowBigLeftIcon
activity.filterAccounts=xpath=//*[@resource-id="com.ubs.clientmobile:id/tv_account_selector"]
activity.selectAll=xpath=//*[@resource-id="com.ubs.clientmobile:id/btn_select_all"]
activity.apply=xpath=//*[@resource-id="com.ubs.clientmobile:id/btn_apply"]


#Ipad
accounts.balances=name=Balances
accounts.currentBalance=name=Current Balance
accounts.holdings=xpath=//*[@text="Cash/Money Funds/Bank Balances"]
holdings.filterAccounts=xpath=//*[@resource-id="com.ubs.clientmobile:id/tv_account_selector"]
holdings.selectAll=//*[@resource-id="com.ubs.clientmobile:id/btn_select_all"]
holdings.apply=xpath=//*[@resource-id="com.ubs.clientmobile:id/btn_apply"]
holdings.cash=name=Cash
accounts.activity=xpath=//*[@text="Activity"]
activity.account=name=Account No.
ipad.activity.account=xpath=//XCUIElementTypeOther[@name='Date']/XCUIElementTypeStaticText[@label='Account No.']
filter.apply=xpath=//*[@resource-id="com.ubs.clientmobile:id/btn_apply"]
ytd=name=Year to date
ytd.android=xpath=//*[@resource-id="com.ubs.clientmobile:id/rb_year_to_year"]
android.movenext=xpath=//*[@name="cdx-arrowBigRightIcon"]
android.account.select.all.button=name=Select All
android.account.apply.button=name=Apply
filter.btn=xpath=//*[@resource-id="com.ubs.clientmobile:id/tv_filter"]
ipad.filter=xpath=(//XCUIElementTypeButton[@label='Filter']/ancestor::XCUIElementTypeOther/XCUIElementTypeButton)[3]
activity.type=name=Activity Type
ipad.activity.type=xpath=//XCUIElementTypeOther[@name='Date']/XCUIElementTypeStaticText[@label='Activity Type']
accounts.financial.tools=xpath=//*[@text="Financial Tools"]
financial.tools.msg=name=Information on this page is refreshed daily and does not reflect real time values
net.balance=name=Net Balance
cash.flow.android=xpath=//*[@text="Cash flow"]
cash.flow=xpath=//*[@text="Cash flow"]
cash.flow.msg=name=Know how your money moves
cash.flow.spending=xpath=//*[@text="Spending"]
cash.flow.expenses=name=Expense Analysis
back=xpath=//*[@label="cdx arrow small left"]
balances.priorday=name=Prior day
ipad.balances.selected.type=xpath=//*[@name='Intraday']/following-sibling::XCUIElementTypeOther/XCUIElementTypeStaticText
ipad.balances.priorday=xpath=//*[@name='Intraday']/following-sibling::XCUIElementTypeStaticText
prior.day.investments=name=investmentHeaderCell
ipad.prior.day.investments=xpath=//*[@name='investmentHeaderCell']/XCUIElementTypeStaticText[@name='Investments ']
balances.intraday=name=Intraday
balances.all=name=All
ipad.balances.selected.accounts=xpath=//*[@name='UBS']/following-sibling::XCUIElementTypeOther/XCUIElementTypeStaticText
ipad.balances.all=xpath=//*[@name='UBS']/following-sibling::XCUIElementTypeStaticText
all.assets=name=Assets
ipad.all.assets=xpath=//XCUIElementTypeTable//XCUIElementTypeButton[@label='Assets']
ubs=name=UBS
android.djia.asof=xpath=//*[@resource-id="com.ubs.clientmobile:id/rv_market_data"]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/*[@resource-id="com.ubs.clientmobile:id/tv_timestamp"]

#//*[@resource-id='com.ubs.clientmobile:id/tv_timestamp'][5]
#//*[@resource-id="com.ubs.clientmobile:id/tv_timestamp"]
#//*[@resource-id="com.ubs.clientmobile:id/rv_market_data"]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]
holdings.ubs.change=name=Change in Value
holdings.quantity=name=Quantity
activity.amounts=xpath=//XCUIElementTypeStaticText[starts-with(@label,'$')]
ipad.holdings.grandTotal=xpath=(/descendant-or-self::node()/XCUIElementTypeStaticText[@value="Total Value"])[1]/following-sibling::XCUIElementTypeStaticText[1]
android.activity.back=xpath=//*[@resource-id="com.ubs.clientmobile:id/toolbar_back"]
# Milestone
mile.scouts=xpath=//*[@text="donation to the Scouts"]
mile.back.ipad=name=Button
mile.bsa=xpath=//*[@resource-id="com.ubs.clientmobile:id/tv_relationship"]
mile.resources=name=Resources
mile.back=name=cdx arrowBigLeftIcon
mile.add=name=Add a milestone
mile.travel=name=Travel
mile.name=name=MilestoneNameComponentViewCell
mile.next=name=Next
mile.start=name=milestoneStartYear
mile.year=name=2024
mile.amount=name=milestoneAmount
mile.add.keyboard=xpath=//*[@label="addMilestoneTableView"]/XCUIElementTypeOther[1]
milestones.page=name=The road ahead
milestone.created=xpath=//*[@label="London"]
milestone.delete=name=Remove this milestone
milestone.delete.confirm=name=Delete
retirement=name=Retirement
something.went.wrong=xpath=//*[@label="Sorry, something went wrong"]

#Ipad
xbutton=xpath=//XCUIElementTypeButton[@label="Button"]

###################### Profile ##############

#android
profile.android.primary=xpath=//*[@resource-id="com.ubs.clientmobile:id/tv_primary_email"]
profile.android.team=xpath=//*[@text="My UBS Team"]
profile.android.advice=name=Chris
profile.meetings=name=Meetings
profile.no.meeting=name=No upcoming meetings
profile.settings=name=Settings
profile.card=name=Card Security
profile.nocard=name=There is no card to manage
profile.card.back=name=cdx arrowBigLeftIcon
support.close=xpath=//*[@resource-id="com.ubs.clientmobile:id/image_close_support"]
feedback.send=xpath=//*[@resource-id="com.ubs.clientmobile:id/button_send"]
profile.my.information=xpath=//*[@resource-id="com.ubs.clientmobile:id/menus_list"]/android.view.ViewGroup[1]/android.widget.ImageView[1]

#ipad
profile.primary=name=Primary
profile.relationship=xpath=//*[@text="Relationships"]
profile.team=xpath=//*[@label="Empty list"]/XCUIElementTypeOther[2]/XCUIElementTypeButton[4]
close.tome=name=Close to Me
mindset=xpath=//*[@resource-id="com.ubs.clientmobile:id/menus_list"]/android.view.ViewGroup[4]
mindset.msg=name=Has your outlook changed?
menu.settings=xpath=//*[@resource-id="com.ubs.clientmobile:id/menu_settings"]
information=name=Information
profile.back=name=cdx arrow small left
profile.return=xpath=//XCUIElementTypeButton[@label='cdx arrow small left']
#support=name=Support
android.support.need.assistance=xpath=//*[@text='Need assistance? Call']
android.menu.support=xpath=//*[@resource-id="com.ubs.clientmobile:id/menus_list"]/android.view.ViewGroup[5]
support.done=xpath=//*[@text="Done"]
feedback=xpath=//*[@text="Feedback"]
feedback.cancel=xpath=//*[@text="Cancel"]
external.pro=name=External Professionals
community.bsa=name=BSA
ipad.card.security=xpath=//AppiumAUT/XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[2]/XCUIElementTypeOther[1]/XCUIElementTypeTable[1]/XCUIElementTypeCell[5]/XCUIElementTypeButton[1]

######## Menu Options ######
#android
relationship.community=name=Community
#  //*[@label="Empty list"]/XCUIElementTypeOther[2]/XCUIElementTypeButton[3]
relationship.team=name=My UBS Team
relationship.advice=name=UBS Wealth Advice Center
interest=name=Has your perspective changed?
settings.reset=name=Reset Password
androidlegal.cancel=xpath=//*[@resource-id="com.ubs.clientmobile:id/image_close_support"]

##FA
#Ipad
contact=xpath=//XCUIElementTypeButton[@label="Contact your Financial Advisor"]
tollfree=name=Toll Free
close=name=Close
ipad.setttings.close=xpath=//XCUIElementTypeButton[@label="close"]